dist: trusty
language: scala
scala:
    - 2.13.2

# This may be necessary depending on the tests we eventually run. For example,
# the chaincode base server uses "java.util.Base64", which is only supported
# as of java version 8
jdk:
  - oraclejdk8

before_install:
  - ./travis_specific/install-protobuf.sh
  - ./travis_specific/install-solc.sh
  - curl -sSL http://bit.ly/2ysbOFE | bash -s 1.4.1 -s
  - mv bin $HOME
  - export PATH=${PATH}:${HOME}/protobuf/
  - export PATH=${PATH}:${HOME}/solc/
  - export PATH=${PATH}:${HOME}/bin/


script:
  - gradle publish -b Obsidian_Runtime/build.gradle
  - sbt ++2.13.2 test
  - bash travis_specific/tests.sh

cache:
  directories:
  - $HOME/.m2
